#!/usr/bin/env python3
#define question 1
def q1():
    print("Should you eat that burger!? ")
    print("Please only answer Yes or No")
    print("Do you want to feel like angels are frolicking on your taste buds?")
    ans = input("YES or NO")

    if ans == "yes":
        print("EAT IT!")
    
    elif ans == "no":
        q2()
#define question 2
def q2():
    print("You've clearly never tasted a burger. Are you afraid it will kill you?")
    ans = input("YES or NO")
    
    if ans == "yes":
        print("Coward")
        q3()
    
    elif ans == "no":
        print("EAT IT!")
        

#define question 3
def q3():
     while True:
        print("Are you REALLY a coward?")
        ans = input("YES or NO")

        if ans == "yes":
            print("Burgers will not only turn you into a true warrior, they will fill your soul with joy!")       
            break 
        
        else:  
            print("Then what is the real issue?")
            q4()
#define queston 4
def q4():
    print("Do you have a pet cow?")
    ans= input("YES or NO")
    
    if ans == "yes":
        print("Great more burgers!")
       # break 

    elif ans == "no":
        print("I really don't see the issue here")
        q3()

if __name__ == "__main__":
    q1()
