#!/usr/bin/env python3
name= input("What is your name?")
day= input("What day of the week is today?")

# Objects
#print("Hello,"  name , "! Happy", day, "!", sep="")

#Concatenation
print("Hello, " + name + "! Happy " + day + "!")

